apiVersion: v1
kind: Pod
metadata:
  name: redi-pod
  labels:
    name: redi-pod
    app: demo-voting-app
spec: 
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379